name: 'g++-11 installation test'

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: add-apt-repo
        uses: pheiduck/actions-install-and-cache@v1
        with:
          cache: workflow
          sudo: true
          run: |-
            add-apt-repository -y ppa:ubuntu-toolchain-r/test
            apt update
          path: /etc/apt /var/lib/apt /var/lib/waagent
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: g++-11
          method: timestamp
      - run: |
          g++-11 --version
      - run: test "${{ steps.action.outputs.cache-hit }}" != true

  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: add-apt-repo
        uses: pheiduck/actions-install-and-cache@v1
        with:
          cache: workflow
          sudo: true
          run: |-
            add-apt-repository -y ppa:ubuntu-toolchain-r/test
            apt update
          path: /etc/apt /var/lib/apt /var/lib/waagent
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: g++-11
          method: timestamp
      - run: |
          g++-11 --version
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
